### ISSUE TITLE
Error during "Fetching order numbers from Device42"

### ISSUE THREAD

**Issue by adarobin** [device42/warranty_check#12]
I just received our API key from Dell today so I was trying to get this working on a Windows box, but I'm not having much luck.  This is what I see when I attempt to run:

```
C:\Scripts\warranty_check>c:\Python27\python.exe starter.py

[!] Fetching order numbers from Device42
Traceback (most recent call last):
  File "starter.py", line 16, in <module>
    main()
  File "starter.py", line 8, in main
    dell.main()
  File "C:\Scripts\warranty_check\Files\warranty_dell.py", line 117, in main
    if orders and orders.has_key('purchases'):
AttributeError: 'list' object has no attribute 'has_key'
```

**Comment by ghost** [comment]
Hello @adarobin, can you check how it working now ? Please, pull last version of code.

**Comment by adarobin** [comment]
Hi @tolyadouble, I no longer get the error fetching order numbers from Device42.  The script ran for a while, but eventually crashed checking warranty info:

```
        [+] Checking warranty info for Dell "REDACTED"
Traceback (most recent call last):
  File ".\starter.py", line 16, in <module>
    main()
  File ".\starter.py", line 8, in main
    dell.main()
  File "C:\Scripts\warranty_check\Files\warranty_dell.py", line 145, in main
    warranty = dell.run_warranty_check(serial)
  File "C:\Scripts\warranty_check\Files\warranty_dell.py", line 37, in run_warra
nty_check
    result  = resp.json()
  File "c:\Python27\lib\site-packages\requests\models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by ghost** [comment]
Thanks for the feedback, can you provide your Windows and Python versions ?
( write `python -V` )

**Comment by adarobin** [comment]
Windows 2012 R2
```
C:\>c:\Python27\python.exe -V
Python 2.7.12
```

**Comment by adarobin** [comment]
I thought I was onto what caused this, but now I am not sure.  The serial number that was having the issue had an "Asset Lifecycle" set on the device.  I deleted this information and the serial number processed successfully.  However, I now have a different serial number that is having problems that does not have an "Asset Lifecycle" so I am a bit stumped.

**Comment by ghost** [comment]
Can you open `C:\Scripts\warranty_check\Files\warranty_dell.py` and above this string `result  = resp.json()` add `print resp` ?
then please write stack trace here

**Comment by adarobin** [comment]
I also added a `print resp.text `after the `print resp`.  It appears there is a rate limit for the API.

```
<Response [401]>

<Fault xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://api.dell.com/faults">
<Code xmlns="">eAPI-40120</Code>
<Url xmlns="">http://developer.dell.com/faults#eAPI-40120</Url>
<Message xmlns="">Service Profile Throttle Limit Reached</Message>
<Reason xmlns="">User application has exceeded the burst rate per minute</Reason>
<Source xmlns="">Gateway</Source></Fault>
```

**Comment by ghost** [comment]
Looks like rate refreshing every minute, so you may try again soon.

**Comment by ghost** [comment]
Seems I've found issue, let me fix it. Thanks.

**Comment by ghost** [comment]
Please pull new version and test.

**Comment by adarobin** [comment]
That seems to have done the trick, slowed it down a bit though (obviously).

Could probably rewrite it to put multiple serial numbers in the same API request to speed things up, but seeing as its working now I can't complain :-)

**Comment by ghost** [comment]
We will check about possibility :) thanks

**Comment by adarobin** [comment]
Just as an FYI, this is the response I got from Dell as to what the rate limits are.

> Below are few rate-limiting mechanisms to be managed. Kindly have a delay between the calls to control the batch process.


> *	Daily Quota: specifies a maximum request limit per day -  5K calls/day each call can accommodate 70 service tags
> *	Monthly Quota: specifies a maximum request limit for the month - 5K*30
> *	Burst Rate: specifies a maximum spike of requests allowed per minute - 45 calls/minute wherein you can push 70 service tags in each call
> 
> Considering you are running the report for ~300 servers, I assume the only control required would be to restrict 70 service tags in one batch/call.
