### ISSUE TITLE
Error with IBM check

### ISSUE THREAD

**Issue by adarobin** [device42/warranty_check#15]
When the IBM check attempts to run I see this error:
```
[+] Ibm serial #: REDACTED
        [+] Checking warranty "REDACTED"
        [+] Checking possible product "REDACTED"
Traceback (most recent call last):
  File "starter.py", line 145, in <module>
    loader(vendor, vendor_api, d42_rest)
  File "starter.py", line 98, in loader
    result = vendor_api.run_warranty_check(inline_serials)
  File "C:\Scripts\warranty_check\Files\warranty_ibm_lenovo.py", line 73, in run
_warranty_check
    current_product = product_info[0]
IndexError: string index out of range
```

**Comment by ghost** [comment]
Hi @adarobin, did it work before for this serial? Do you have this issue for other IBM serials?

**Comment by adarobin** [comment]
Hi @tolyadouble, it worked fine for all of my Dell machines.  I literally only have 1 IBM machine in my Device42 system.

**Comment by ghost** [comment]
Our IBM keys works good. Is it possible to send your key to support@device42.com ? So we can troubleshoot

**Comment by adarobin** [comment]
I just sent an e-mail with the serial number and model info.

**Comment by ghost** [comment]
Thanks. Btw, please check `warranty.cfg.example`, especially section `[ibm]`. At your config should be exactly the same.

**Comment by adarobin** [comment]
My config looks right compared to the sample config.
`
[ibm]
url = http://support.lenovo.com/services/us/en/ContentService/GetProducts
url2 = http://support.lenovo.com/us/en/products
`

I did a little digging, and this machine is in storage (not hooked up).  It's possible one of our student workers typo'd some of the data for it.

**Comment by ghost** [comment]
Seems like issue with IBM checking gateway, no information for this serial.
You may write to IBM support about it.
I've put code that catch this case. And I think we may close this issue.

**Comment by adarobin** [comment]
Sounds good, thanks.

**Comment by ghost** [comment]
Here is page where you can manually check "IBM\LENOVO" serials.
[http://support.lenovo.com/us/en/warrantylookup](http://support.lenovo.com/us/en/warrantylookup)

**Comment by ghost** [comment]
@adarobin can you try to get warranty data here 
[https://www-947.ibm.com/support/entry/portal/wlup](https://www-947.ibm.com/support/entry/portal/wlup) ? Does it work for you ?

**Comment by adarobin** [comment]
@tolyadouble I tried that and it throws an error so it must either be bad data or IBM doesn't have the info for some reason.

**Comment by ghost** [comment]
@adarobin, ok, if you are going to reach IBM support and they write some useful information that allow you to get warranty data for current key, please write here or support@device42.com, maybe it may help us improve our script. Thanks.
