### ISSUE TITLE
Readme needs update (Dell API)

### ISSUE THREAD

**Issue by Roddd** [device42/warranty_check#19]
The Dell API key is no longer at this URL:
http://en.community.dell.com/dell-groups/supportapisgroup/m/mediagallery/20428185

It's been moved to their TechDirect site and requires logging in.
https://techdirect.dell.com/Portal.30/APIs.aspx

See http://en.community.dell.com/dell-groups/supportapisgroup/ for details.

**Comment by ghost** [comment]
Hi @Roddd, thanks!
