### ISSUE TITLE
Issues retreiving job from HP API

### ISSUE THREAD

**Issue by Davewarrington** [device42/warranty_check#20]
Running the latest version, HP Serials only .. getting the following error on job retrieval. 

[+] Waiting 5 seconds before getting job result
[+] Checking API Job "bb1b9232-cc72-4d94-ae4c-c37*********"
[+] Waiting 5 seconds before getting job result
[!] Retry
[+] Checking API Job "bb1b9232-cc72-4d94-ae4c-c37*********"
[!] Fail, please try again later

**Comment by ghost** [comment]
Hello @Davewarrington this is an issue with HP's APIs. HP's APIs to get this info is in early stages. We have already written to dev team and are waiting on a response from them. If you are able to get some help from enterprise level support for this from HP. that will help.

**Comment by thomsonac** [comment]
I get a similar error.  Any news from HPE?

Traceback (most recent call last):
  File "starter.py", line 155, in <module>
    loader(vendor, vendor_api, d42_rest)
  File "starter.py", line 92, in loader
    result = vendor_api.run_warranty_check(inline_serials)
  File "C:\it\Scripts\Device42\warranty_check\Files\warranty_hp.py", line 166, in run_warranty_check
    if self.check_job(job) is None:
  File "C:\it\Scripts\Device42\warranty_check\Files\warranty_hp.py", line 104, in check_job
    print '\t[+] Checking API Job "%s"' % job['jobId']

**Comment by ghost** [comment]
hi @thomsonac, can you copy full stack trace here ?

**Comment by thomsonac** [comment]
C:\it\Scripts\Device42\warranty_check>python starter.py

[!] Fetching order numbers from Device42

[+] hp section
        [+] Getting HP access token

[!] Fetching hardware models from Device42

[!] Fetching devices from Device42 with offset=0
[+] Hp serial #: <REDACTED Big list>

        [+] Checking warranty info for "<REDACTED Big list>"
        [+] Prepare API Job for "<REDACTED Big list>"
        [+] Waiting 5 seconds before getting job result
        [+] Checking API Job "1300a629-7e4c-4bdb-a4d8-..."
        [+] Waiting 5 seconds before getting job result
        [!] Retry
        [+] Checking warranty info for "<REDACTED Big list>"
        [+] Prepare API Job for "<REDACTED Big list>"
        [+] Waiting 5 seconds before getting job result
        [+] Checking API Job "8c4e2b54-4527-44c7-b542-..."
        [+] Waiting 5 seconds before getting job result
        [!] Retry
        [+] Checking API Job "8c4e2b54-4527-44c7-b542-..."
        [!] Fail, please try again later

[!] Fetching hardware models from Device42

[!] Fetching devices from Device42 with offset=50
[+] Hp serial #: <REDACTED Big list>

        [+] Checking warranty info for "<REDACTED Big list>"
        [+] Prepare API Job for "<REDACTED Big list>"
        [+] HP API issue, trying again

[!] Retry
        [+] Prepare API Job for "<REDACTED Big list>"
        [+] Waiting 5 seconds before getting job result

Traceback (most recent call last):
  File "starter.py", line 155, in <module>
    loader(vendor, vendor_api, d42_rest)
  File "starter.py", line 92, in loader
    result = vendor_api.run_warranty_check(inline_serials)
  File "C:\it\Scripts\Device42\warranty_check\Files\warranty_hp.py", line 166, in run_warranty_check
    if self.check_job(job) is None:
  File "C:\it\Scripts\Device42\warranty_check\Files\warranty_hp.py", line 104, in check_job
    print '\t[+] Checking API Job "%s"' % job['jobId']
TypeError: 'NoneType' object has no attribute '__getitem__'

C:\it\Scripts\Device42\warranty_check>

**Comment by ghost** [comment]
@thomsonac thanks, can you confirm that you use latest script version? Git fast-forward or clone repository again please, then run and write result.

**Comment by thomsonac** [comment]
I can confirm I'm using the latest version of the script.  Downloaded it late last week

**Comment by ghost** [comment]
@thomsonac can you download latest version, I've made a fix that possible make it works in your case, because I suspected that sometimes HP API need a bit more time for proper get finished job.

**Comment by thomsonac** [comment]
Bombed but slightly different output:

        [+] Waiting 5 seconds before getting job result
        [+] Checking API Job "62e48f5e-e8bc-4774-bebc-...."
Traceback (most recent call last):
  File "starter.py", line 155, in <module>
    loader(vendor, vendor_api, d42_rest)
  File "starter.py", line 95, in loader
    api.process_result(result, purchases)
  File "C:\it\Scripts\Device42\warranty_check\Files\warranty_hp.py", line 197, in process_result
    if item['type'] is None:
TypeError: string indices must be integers

**Comment by ghost** [comment]
@thomsonac File `Files\warranty_hp.py` After line 173, please add `print result`, should be like this :
```
            ....
            result = resp.json()
            print result
            if 'fault' in result:
            ....
```
then please copy stack trace here.

**Comment by Davewarrington** [comment]
Traceback (most recent call last):
  File "C:\Device42\warranty_check-master\starter.py", line 6, in <module>
    from Files.warranty_hp import Hp
  File "C:\Device42\warranty_check-master\Files\warranty_hp.py", line 174
    print result,
    ^
IndentationError: unexpected indent

**Comment by ghost** [comment]
hi @Davewarrington, you put wrong indent, please use 4 spaces instead tabs, for the line `print result`, also plesae check that `print result` comes without comma at the end. Btw do you have the same issue as @thomsonac ?

**Comment by Davewarrington** [comment]
Same Issue i'm afraid.  I'll attempt to test again now ...

**Comment by Davewarrington** [comment]
Job ran, however, error now is ...

Traceback (most recent call last):
  File "C:\Device42\warranty_check-master\starter.py", line 155, in <module>
    loader(vendor, vendor_api, d42_rest)
  File "C:\Device42\warranty_check-master\starter.py", line 95, in loader
    api.process_result(result, purchases)
  File "C:\Device42\warranty_check-master\Files\warranty_hp.py", line 198, in pr
ocess_result
    if item['type'] is None:
TypeError: string indices must be integers

**Comment by ghost** [comment]
@Davewarrington can you copy full output ( with information before `Traceback` ) ?

**Comment by Davewarrington** [comment]
@tolyadouble  full output as requested 

        [+] Checking warranty info for "REDACTED "
        [+] Prepare API Job for "REDACTED "
        [+] Waiting 5 seconds before getting job result
        [+] Checking API Job "7cf81531-4592-430d-a587-...."
{u'message': u'An error has occurred.'}
Traceback (most recent call last):
  File "C:\Device42\warranty_check-master\starter.py", line 155, in <module>
    loader(vendor, vendor_api, d42_rest)
  File "C:\Device42\warranty_check-master\starter.py", line 95, in loader
    api.process_result(result, purchases)
  File "C:\Device42\warranty_check-master\Files\warranty_hp.py", line 198, in p
ocess_result
    if item['type'] is None:
TypeError: string indices must be integers

**Comment by ghost** [comment]
@Davewarrington thanks. Seems I almost found the problem. Can you try latest script version ?

**Comment by Davewarrington** [comment]
@tolyadouble  Closer


[+] Hp serial #: .......
        [+] Checking warranty info for "......"
        [+] Prepare API Job for "......"
        [+] Waiting 5 seconds before getting job result
        [+] Checking API Job "9fffb3a3-9d04-4586-....-...."
        [+] Waiting 5 seconds before getting job result
        [!] Retry
        [+] Checking API Job "9fffb3a3-9d04-4586-....-...."
        [!] Fail, please try again later

**Comment by ghost** [comment]
@Davewarrington another try please :1st_place_medal: , download latest.

**Comment by Davewarrington** [comment]
@tolyadouble  Took a while (30 mins per check) but the answer was not good 

        [+] Checking warranty info for "......."
        [+] Prepare API Job for "......"
        [+] Please wait... checking job status...
        [+] Checking API Job "12ac75f4-dd48-498c-9995-..."
        [+] Please wait... checking job result...
        [+] Waiting 5 seconds before getting job result
        [!] Retry
        [+] Checking warranty info for "......"
        [+] Prepare API Job for "......"
        [+] Please wait... checking job status...
        [+] Checking API Job "819b0ef4-3650-49ce-b17b-..."
        [+] Please wait... checking job result...
        [!] Fail, please try again later

**Comment by thomsonac** [comment]
Downloaded the latest.  I get the same initial output then the following:

        [+] Please wait... checking job status...
        [+] Checking API Job "4379dce9-b94c-492b-b45b-..."

[!] HTTP error. Message was: HTTPSConnectionPool(host='css.api.hp.com', port=443): Read timed out. (read timeout=30)

**Comment by ghost** [comment]
@thomsonac, this error means that script can't connect to the `css.api.hp.com`, maybe rerun ?

**Comment by thomsonac** [comment]
Looks like a successful run.  Thanks for all of the help

**Comment by ghost** [comment]
@thomsonac great, thanks for your help.

@Davewarrington I'm worry that in your case you have serial in payload that HP cannot correct process and return error.

**Comment by Davewarrington** [comment]
@tolyadouble  Yes also, I feaar this maybe the case ... altho trying to identify which one .. I'll get digging here...

**Comment by ghost** [comment]
@Davewarrington you may try to figure it out manually, here : https://developers.hp.com/css/api/product-warranty-api-0

**Comment by Davewarrington** [comment]
@tolyadouble  the Authorization syntax all way threw me off here,  While I can get an access_token, It doesnt seem happy when i try to load it in to the  Auth field

**Comment by ghost** [comment]
@Davewarrington you need just copy "apiKey" and "apiSecret" that you use and get "access_token" from endpoint. Then copy "access_token" from the response. Then make calls with "Authorization: Bearer _._yourToken_._

**Comment by Davewarrington** [comment]
ahh @tolyadouble  I was missing "Bearer" 


curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer **********' -d '2UX003059X' 'https://css.api.hp.com/productWarranty/v1/queries'




Response body however 

{
  "message": "An error has occurred."
}


I realise that says Queries in the url above, but even submitting to the  jobs url produces the same  error

**Comment by ghost** [comment]
@Davewarrington please read HP API docs and samples, I'm not sure that you make correct request.

**Comment by ghost** [comment]
@Davewarrington how is it going ? Can you make it work ?

**Comment by Davewarrington** [comment]
@tolyadouble I can get a token, submit a job, but having issues then retrieving the jobid .. 

I get a 200 Ok, on the submission of the Serial  .. 


curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer xxxxxxxxxxxxxxxxxxxxx' -d '[{"sn": "2UX003059X"}] \ 
 ' 'https://css.api.hp.com/productWarranty/v1/jobs'

**Comment by ghost** [comment]
@Davewarrington in response of the call above should be `jobId` that you can use in `/productWarranty/v1/jobs/' + job['jobId'] + '/results`

**Comment by Davewarrington** [comment]
@tolyadouble 

whats intersting is when i attempt this 

curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer xxxxxx' 'https://css.api.hp.com/productWarranty/v1/jobs/0cc2e957-9b50-4d5f-b1f4-e0ce7c5788e3/results'

I get

 {
  "message": "An error has occurred."
}

However ! I can submit a one time job  via 


curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer xxxxxxxxxx' -d '[{"sn": "2UX003059X"}]' 'https://css.api.hp.com/productWarranty/v1/queries'


And it returns the information as expected..

**Comment by ghost** [comment]
Looks like issue on HP side. @Davewarrington thanks for your help.

**Comment by tolyadouble** [comment]
Looks like issue on HP side. @Davewarrington thanks for you help.

**Comment by Davewarrington** [comment]
I agree,  I'll e-mail dev in HP ! Thanks @tolyadouble

**Comment by ghost** [comment]
@Davewarrington please keep us posted with their response, Support@device42.com
