### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by denisbrodsky** [device42/warranty_check#25]
Hello, 
I am trying to run the script in my environment and getting the following issue with Lenovo disccovery:
        [+] Checking warranty "PF0YGGMG,PC0YMT12,PC041X7D,PC0KEL3C,PC04W5AY,PC04W5AU,PC0DLDYY,PC0EAMV2,PC0KEL2Y,PC04W5AZ,PC050NXP,PC0EAMVM,PF0QRJD8,PC0EAMWF,PC0RKQ3X,PC0SYDM2,PC0RKQ46,PC0RKQ2S,PC0RKQ2J,PC0RKQ3S,PC090UQ8,PC050NXU,PC0DLDW3,PC090UMB,PC050P06,PC0SYDLC,PC090UQ9,PC0EAMW8,PC041X77,PC0DLDW1,PF0XPPKU,PF0YGJTC,PC0E4ZGB,PF0REZ9Y,PF0ZJ9A5,PF0L02C8,PF0ZJ9AK,PF0ZJ99D"
        [+] Checking possible product "PF0YGGMG"
Traceback (most recent call last):
  File "starter.py", line 155, in <module>
    loader(vendor, vendor_api, d42_rest)
  File "starter.py", line 92, in loader
    result = vendor_api.run_warranty_check(inline_serials)
  File "C:\Users\dbrodsky\denis\Files\warranty_ibm_lenovo.py", line 100, in run_warranty_check
    json_object = json.loads(data_object.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by osanchez42** [comment]
Hello Denis, I am currently updating the standalone script and making sure that it is still functional for all vendors. Are you still experiencing this issue or were you able to resolve this problem.

**Comment by osanchez42** [comment]
issue has been replicated, Lenovo has updated their API and the warranty script needs to be updated.

**Comment by osanchez42** [comment]
PR in progress
